config/routes.rb
SecretShareAjax::Application.routes.draw do

  resources :users, :only => [:create, :new, :show, :index] do
    resources :secrets, only: [:new]
    resources :friendships, only: [:create, :destroy]
  end
  resources :secrets, only: [:create]
  resource :session, :only => [:create, :destroy, :new]

  root :to => "users#show"
end

app/models/friendship.rb
# == Schema Information
#
# Table name: friendships
#
#  id            :integer          not null, primary key
#  out_friend_id :integer          not null
#  in_friend_id  :integer          not null
#  created_at    :datetime
#  updated_at    :datetime
#

class Friendship < ActiveRecord::Base
  validates :out_friend_id, :in_friend_id, presence: true

  belongs_to :out_friend,
    class_name: "User",
    foreign_key: :out_friend_id

  belongs_to :in_friend,
    class_name: "User",
    foreign_key: :in_friend_id

  def self.can_friend?(out_friend_id, current_user)
    !(out_friend_id == current_user.id ||
    current_user.out_friends.include?(User.find(out_friend_id)) ||
    current_user.in_friends.include?(User.find(out_friend_id)))
  end


end

app/models/secret.rb
# == Schema Information
#
# Table name: secrets
#
#  id           :integer          not null, primary key
#  title        :string(255)      not null
#  author_id    :integer          not null
#  recipient_id :integer          not null
#  created_at   :datetime
#  updated_at   :datetime
#

class Secret < ActiveRecord::Base

  validates :author_id, :recipient_id, :title, :presence => true

  belongs_to :author, :class_name => "User"
  belongs_to :recipient, :class_name => "User"

  has_many :secret_taggings
  has_many :tags, through: :secret_taggings
end

app/models/secret_tagging.rb
# == Schema Information
#
# Table name: secret_taggings
#
#  id         :integer          not null, primary key
#  secret_id  :integer          not null
#  tag_id     :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class SecretTagging < ActiveRecord::Base

  validates :secret_id, :tag_id, presence: true

  belongs_to :secret
  belongs_to :tag
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  text       :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#

class Tag < ActiveRecord::Base
  validates :text, presence: true

  has_many :secret_taggings
  has_many :secrets, through: :secret_taggings

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)      not null
#  password_digest :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#  session_token   :string(255)      not null
#

class User < ActiveRecord::Base
  attr_reader :password

  has_many(
    :authored_secrets,
    :class_name => "Secret",
    :foreign_key => :author_id
  )

  has_many(
    :received_secrets,
    :class_name => "Secret",
    :foreign_key => :recipient_id
  )
  #friendships where you requested
  has_many :out_friendships,
    class_name: "Friendship",
    foreign_key: :out_friend_id


  #friendships where you were requested
  has_many :in_friendships,
    class_name: "Friendship",
    foreign_key: :in_friend_id

  #friends that requested you
  has_many :in_friends, through: :in_friendships, source: :in_friend

  #friends that we requested
  has_many :out_friends, through: :out_friendships, source: :in_friend

  validates :password_digest, :presence => { :message => "Password can't be blank" }
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true
  validates :username, :presence => true

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user, :signed_in?

  def current_user
    return nil unless session[:session_token]
    User.find_by_session_token(session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logout_current_user!
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end

  def require_current_user!
    redirect_to new_session_url unless signed_in?
  end

  def require_no_current_user!
    redirect_to user_url(current_user) if signed_in?
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    @friendship = Friendship.new(friendship_params)
    @friendship.out_friend_id = current_user.id
    @friendship.save!

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { render :json => @friendship }
    end
  end

  def destroy
    @friendship = Friendship.find(params[:id])
    @friendship.destroy!

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { render :json => @friendship }
    end
  end


  private

  def friendship_params
    params.require(:friendship).permit(:in_friend_id)
  end
end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  def new
    @secret = Secret.new
    @user = User.find(params[:user_id])
  end

  def create
    @secret = Secret.new(secret_params)
    @secret.author_id = current_user.id

    @secret.try(:save)

    respond_to do |format|
      # format.html { redirect_to users_url }
      format.json { render json: @secret }
    end


  end

  private
  def secret_params
    params.require(:secret).permit(:title, :recipient_id, :tag_ids => [])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :require_no_current_user!, :only => [:create, :new]
  before_filter :require_current_user!, :only => [:destroy]

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user.nil?
      render :json => "Credentials were wrong"
    else
      self.sign_in(user)
      redirect_to user_url(user)
    end
  end

  def destroy
    logout_current_user!
    redirect_to new_session_url
  end

  def new
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_current_user!, :only => [:index, :show]
  before_filter :require_no_current_user!, :only => [:create, :new]

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to user_url(@user)
    else
      render :json => @user.errors.full_messages
    end
  end

  def new
    @user = User.new
  end

  def index
    @users = User.all.select do |user|
      user != current_user
    end
  end

  def show
    if !params.include?(:id)
      redirect_to user_url(current_user)
      return
    end
    @tags = Tag.all

    @user = User.find(params[:id])

    respond_to do |format|
      format.html { render :show }
      format.json { render json: @user.received_secrets }
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def can_unfriend?(friend)
    (current_user.in_friends.include?(friend) ||
    current_user.out_friends.include?(friend))
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/friendships/create.html.erb
<h1>Friendships#create</h1>
<p>Find me in app/views/friendships/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SecretShareAjax</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "underscore" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if signed_in? %>
  <ul>
    <li>Logged in as: <%= current_user.username %></li>
    <li><%= button_to "Logout", session_url, :method => :delete %></li>
  </ul>
<% end %>

<%= yield %>

</body>
</html>

app/views/secrets/_form.html.erb
<form class="secret-form" method="post" accept-charset="utf-8">
  <input type="hidden"
    name="authenticity_token" value=""
    id="form_authenticity_token">

    <label for="secret_title">Title:</label><input type="text" name="secret[title]"   value="" id="secret_title">

    <input type="hidden" name="secret[recipient_id]" value="<%= user.id %>" id="secret_recipient_id">

    <select name="secret[tag_ids][]" id="secret_tags_id_0">
      <option value="" ></option>
      <% tags.each do |tag| %>
        <option value="<%= tag.id %>"><%= tag.text %></option>
      <% end %>
    </select>

    <button type="button" class="another-tag">Add another Tag</button>

  <p><input type="submit" class="submit-secret" value="Post"></p>
</form>
<script>
  $(".another-tag").on("click", function(event) {
    event.preventDefault();

    var templateCode = $("#select_template").html()

    var templateFn = _.template(templateCode);

    // var renderedContent = function(){
    //    $("#ideas").html(templateFn({tags: @tags}));
    // }


  })
</script>

<script type="text/template" id="select_template">
    <select name="secret[tag_ids][]" id="secret_tags_id_0">
      <option value="" ></option>
      <%% _(tags).each(function(tag){ %>
        <option value="<%%= tag.id %>"><%%= tag.text %></option>
      <%% }) %>
    </select>
</script>

app/views/secrets/create.html.erb
<h1>Secrets#create</h1>
<p>Find me in app/views/secrets/create.html.erb</p>

app/views/secrets/new.html.erb
<h1>Post a new Secret</h1>

app/views/tags/create.html.erb
<h1>Tags#create</h1>
<p>Find me in app/views/tags/create.html.erb</p>

app/views/tags/destroy.html.erb
<h1>Tags#destroy</h1>
<p>Find me in app/views/tags/destroy.html.erb</p>

app/views/tags/new.html.erb
<h1>Tags#new</h1>
<p>Find me in app/views/tags/new.html.erb</p>

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>

<form action="<%= action %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input
     id="user_username"
     name="user[username]"
     type="text">
  <br>

  <label for="user_password">Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password">
  <br>

  <input type="submit" value="<%= message %>">
</form>

app/views/users/_user.html.erb
<b><%= user.username %></b>

<% if can_unfriend?(user)%>
  <% div_class = "can-unfriend" %>
<% else %>
  <% div_class = "can-friend"%>
<% end %>

<div class="friend-buttons <%= div_class %>" >
  <button type="button" class="friend"
    data-id="<%= user.id %>" >Add Friend</button>

  <button type="button" class="unfriend"
    data-id="<%= user.id %>">Destroy friend :(</button>
  <br>
</div>

app/views/users/index.html.erb
<h1>Users index</h1>

<%= render @users %>
<script>
$(".friend").on("click",function(event){
  event.preventDefault();

  $(event.target).prop("disabled", true)

  var id = parseInt($(event.target).attr("data-id"));



  $.ajax({
    url: "/users/" + id + "/friendships.json",
    type: "POST",
    data: {
      friendship:
      {
        in_friend_id: id
      }
    },
    success: function(data){
      $(event.target).parent().toggleClass('can-friend');
      $(event.target).parent().toggleClass('can-unfriend');
      $(event.target).siblings(".unfriend").attr("data-friendship-id", data.id);
      $(event.target).siblings(".unfriend").prop("disabled", false)
      console.log('success!');
    }
  })
})

$(".unfriend").on("click", function(event){
  event.preventDefault();

  $(event.target).prop("disabled", true)


  var userID = parseInt($(event.target).attr("data-id"));
  var friendshipID = parseInt($(event.target).attr("data-friendship-id"));



  $.ajax({
    url: "/users/" + userID + "/friendships/" + friendshipID + ".json",
    type: "DELETE",
    data: {
      id: friendshipID
    },
    success: function(){
      $(event.target).parent().toggleClass('can-friend');
      $(event.target).parent().toggleClass('can-unfriend');
      $(event.target).siblings(".friend").prop("disabled", false)
      console.log('Destroyed!');
    }
  })
})

</script>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= render "form", :user => @user %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<h2>Secrets</h2>
<ul class='user-secrets-ul'>
  <% @user.received_secrets.each do |secret| %>
    <li><%= secret.title %></li>
  <% end %>
</ul>

Post a secret:
<%= render partial: "secrets/form" , locals: {user: @user, tags: @tags} %>

<script>
  // var secrets = JSON.parse($(".user-secrets-ul").html());
  // debugger
  // $(".submit-secret")[0].preventDefault();

  $(".secret-form").on("submit", function(event) {
    event.preventDefault();
    var userID = parseInt($(this).find('#secret_recipient_id').attr('value'));

    $.ajax({
      url: "/secrets.json",
      type: "POST",
      data: $(this).serialize(),
      success: function () {
        $("#secret_title").val("");
        console.log("success");
        $.ajax({
          url: "/users/" + userID + ".json",
          type: "GET",
          success: function (data) {
            var secrets = data;
            render(secrets);
          }
        });
      }
    });
  })

  var render = function (secrets) {
    var $usUl = $('.user-secrets-ul');
    $usUl.empty();

    _(secrets).each(function(secret){
      $newSecret = $('<li>').text(secret.title);
      $usUl.append($newSecret);
    });

    // $("#user-secrets-ul").html(templateFunction({secrets: secrets}));

  };

</script>